from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models


class Order(models.Model):
    """
    Order that was paid by the user.

    Attributes:
        number (str): Unique order identifier (auto generated).
        status (str): Order status provided by Stripe (succeeded / declined / etc).
        date (datetime): Date and time when the order was created.
        stripePaymentId (str): Unique payment ID generated by Stripe to identify the payment (auto generated by Stripe).
        acquirer (Profile): User who paid for the order, order owner.
        subtotal (float): Money portion for the tickets including tax (no service fee).
        service_fee (float): Money portion for service fee.
        total (Decimal): Charged total (subtotal + service fee).
    """

    number = models.CharField(max_length=50, unique=True, blank=True)
    status = models.CharField(max_length=150, blank=False)
    date = models.DateTimeField(auto_now_add=True)
    stripePaymentId = models.CharField(max_length=50, unique=True, null=True, blank=True)
    acquirer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='orders',
    )
    subtotal = models.DecimalField(max_digits=15, decimal_places=2, default=0,
        validators=[
            MinValueValidator(0)
        ]
    )
    service_fee = models.DecimalField(max_digits=8, decimal_places=2, default=0,
        validators=[
            MinValueValidator(0)
        ]
    )
    total = models.DecimalField(max_digits=16, decimal_places=2, default=0,
        validators=[
            MinValueValidator(0)
        ]
    )

    def __str__(self):
        return f"Order {self.number} made by {self.acquirer}"

    def save(self, *args, **kwargs):
        """
        Overridden save method.
        Auto generates unique order number (EH-ODR-YEAR-ID) on initial save.
        """

        initial = self.pk is None
        super().save(*args, **kwargs)

        if initial:
            self.number = f"EH-ODR-{self.date.year}-{self.id}"
            super().save(update_fields=['number', 'date'])

    @property
    def event(self):
        """Returns the event for which tickets have been purchased in this order."""
        first_ticket = self.tickets.first()
        return first_ticket.price_zone.event if first_ticket else None
