from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator
from django.utils import timezone

class Event(models.Model):
    """
    An event created by a user.

    Attributes:
        name (str): The name of the event, required.
        date (date): The scheduled date of the event, required.
        time (time): The scheduled start time of the event, required.
        location (str): The full address or location of the event, required.
        category (str): The category of the event, required.
        description (str): A detailed description of the event (max 5000 characters), optional.
        organizer (Profile): The user who created the event.
    """
    
    CATEGORIES = [
        ('arts', 'Arts'),
        ('business', 'Business'),
        ('family', 'Family'),
        ('food', 'Food & Drink'),
        ('music', 'Music & Concerts'),
        ('social', 'Social & Comedy'),
        ('sports', 'Sports'),
        ('tech', 'Technology'),
    ]
    
    name = models.CharField(max_length=50)
    # TODO translate users local time to UTC while saving
    date = models.DateTimeField()
    location = models.CharField(max_length=255)
    category = models.CharField(max_length=20, choices=CATEGORIES)
    description = models.TextField(blank=True)
    
    organizer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='events',
    )
    
    def __str__(self):
        return self.name
    
    @property
    def is_past(self):
        """Checks if event date is in the past."""
        return self.date < timezone.now()

    @property
    def days_until(self):
        """Integer days until event (negative for past events)."""
        now = timezone.localtime().date()
        event_day = timezone.localtime(self.date).date()
        return (event_day - now).days


class EventImage(models.Model):
    """
    An image for event.

    Attributes:
        event (Event): The event to which this image relates.
        url(str): The url by which the image can be accessed.
    """
    
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        related_name='images'
    )
    url = models.URLField()

    def __str__(self):
        return f"Image for {self.event.name}"


class EventPriceZone(models.Model):
    """
    A price zone (range of tickets selling for the same price) for the event.
    
    Attributes:
        event (Event): The event to which this price zone relates.
        name (str): The name of the price zone.
        desc (str): Brief description of the price zone.
        price (float): The price of the price zone in USD.
        seats (int): The capacity of seats of the price zone.
    """
    
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        related_name='price_zones'
    )
    name = models.CharField(max_length=30)
    desc = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0,
        validators=[
            MinValueValidator(0)
        ]
    )

    seats = models.PositiveBigIntegerField()

    def __str__(self):
        return f"Price Zone {self.name} for {self.event.name} event"


class Order(models.Model):
    """
    Order that was paid by the user.
    
    Attributes:
        number (str): Unique order identifier (auto generated).
        status (str): Order status provided by Stripe (succeeded / declined / etc).
        stripePaymentId (str): Unique payment ID generated by Stripe to identify the payment (auto generated by Stripe).
        acquirer (Profile): User who paid for the order, order owner.  
        subtotal (float): Money portion for the tickets (no tax or service fee).
        tax (float): Money portion for tax.
        service_fee (float): Money portion for service fee.
    """
    
    number = models.CharField(max_length=50, unique=True, blank=True)
    status = models.CharField(max_length=150, blank=False)
    date = models.DateTimeField(blank=True, null=True)
    stripePaymentId = models.CharField(max_length=50, unique=True, null=True, blank=True)
    acquirer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='orders',
    )
    subtotal = models.DecimalField(max_digits=15, decimal_places=2, default=0,
        validators=[
            MinValueValidator(0)
        ]
    )
    tax = models.DecimalField(max_digits=8, decimal_places=2, default=0,
        validators=[
            MinValueValidator(0)
        ]
    )
    service_fee = models.DecimalField(max_digits=8, decimal_places=2, default=0,
        validators=[
            MinValueValidator(0)
        ]
    )
    total = models.DecimalField(max_digits=16, decimal_places=2, default=0,
        validators=[
            MinValueValidator(0)
        ]
    )
    
    def __str__(self):
        return f"Order {self.number} made by {self.acquirer}"
    
    def save(self, *args, **kwargs):
        initial = self.pk is None
        super().save(*args, **kwargs)
        
        # order number & purchase date auto generation on initial save
        if initial:
            self.date = timezone.now()
            self.number = f"EH-ODR-{self.date.year}-{self.id}"
            super().save(update_fields=['number', 'date'])

    @property
    def event(self):
        first_ticket = self.tickets.first()
        return first_ticket.price_zone.event if first_ticket else None


class Ticket(models.Model):
    """
    Ticket that was purchased.
    
    Attributes:
        number (str): Unique ticket identifier (auto generated).
        price_zone (EventPriceZone): EventPriceZone which ticket is associated with.
        order (Order): Order at which ticket was purchased.
    """
    
    number = models.CharField(max_length=50, unique=True, blank=False)
    price_zone = models.ForeignKey(
        EventPriceZone,
        on_delete=models.CASCADE,
        related_name='tickets'
    )
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name='tickets'
    )
    
    def save(self, *args, **kwargs):
        initial = self.pk is None
        super().save(*args, **kwargs)
        
        # ticket number auto generation on initial save
        if initial:
            year = timezone.now().year
            self.number = f"EH-TCK-{year}-{self.id}"
            super().save(update_fields=['number'])
    
    def __str__(self):
        return f"Ticket {self.number} owned by {self.order.acquirer}"