# Generated by Django 5.2.7 on 2025-12-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinquiry",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
