# Generated by Django 5.2.7 on 2025-11-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
