# Generated by Django 4.1.10 on 2023-08-19 01:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='concert name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='preview image')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('website', models.URLField(max_length=255, verbose_name='website')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(max_length=60, verbose_name='seat type')),
                ('quantity', models.IntegerField(verbose_name='seat quantity')),
                ('price', models.FloatField(verbose_name='price')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.concert')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=20, verbose_name='lastname')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.concert')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.seat')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='Card Number')),
                ('cvv', models.CharField(max_length=4, verbose_name='CVV')),
                ('exp_month', models.CharField(max_length=2, verbose_name='Expiration month')),
                ('exp_year', models.CharField(max_length=4, verbose_name='Expiration year')),
                ('holder_name', models.CharField(max_length=100, verbose_name='Card Holder Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='order date')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.payment')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.user')),
                ('tickets', models.ManyToManyField(to='events.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='managers',
            field=models.ManyToManyField(to='events.user'),
        ),
    ]
