# Generated by Django 5.2.7 on 2025-12-01 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="team",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users allowed to validate tickets for this event.",
                related_name="team_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
