# Generated by Django 5.2.7 on 2025-11-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripePaymentId',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
